### ISSUE TITLE
Slug appended to SEO title in snippet editor

### ISSUE THREAD

**Issue by monbauza** [Yoast/t3ext-yoast-seo#23]
When the _Slug_ field is not filled in, the snippet shows the SEO title in the permalink

![image](https://cloud.githubusercontent.com/assets/9658774/21082196/06d1bf84-bfd7-11e6-9480-55aad4233583.png)

When the _Slug_ field is filled in, the provided slug should replace the SEO title in the permalink. Instead, the snippet editor appends the provided slug to the SEO title.

![image](https://cloud.githubusercontent.com/assets/9658774/21082185/d512e05e-bfd6-11e6-859f-25709bed9fe8.png)

**Comment by omarreiss** [comment]
I don't know if you can control the slug from here. If you can, then this should be fixed. If not, the slug field should be hidden.

**Comment by haassie** [comment]
In #30 I have chosen to hide the slug field for now because I can't really control the generation of the permalink. In TYPO3 the generation of the URL is based on the path the page is in and you only want to override the part you are currently working on. So for now it is a no-fix, but I created #31 to have the function reenabled again.
